environment:
  matrix:
    - GENERATOR: "Visual Studio 12 Win64"
      CONFIG: Debug

    - GENERATOR: "Visual Studio 12 Win64"
      CONFIG: Release

build_script:
  - appveyor.bat

test_script:
  - test\testrun.bat
